// generated by newgenasym  Thu Aug 25 09:56:39 2016


module rj45_dual_jgl_0001nl (\+led1_ , \+led2_ , \+md1_ , \+md2_ , \+md3_ , \+md4_ , \-led1_ , \-led2_ ,
        \-md1_ , \-md2_ , \-md3_ , \-md4_ , mdct1_, mdct2_, mdct3_, mdct4_);
    inout \+led1_ ;
    inout \+led2_ ;
    inout \+md1_ ;
    inout \+md2_ ;
    inout \+md3_ ;
    inout \+md4_ ;
    inout \-led1_ ;
    inout \-led2_ ;
    inout \-md1_ ;
    inout \-md2_ ;
    inout \-md3_ ;
    inout \-md4_ ;
    inout mdct1_;
    inout mdct2_;
    inout mdct3_;
    inout mdct4_;


    initial
        begin
        end

endmodule
