-- generated by newgenasym Thu Aug 25 09:56:39 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_dual_jgl_0001nl is
    port (    
	\+led1_\:  INOUT  STD_LOGIC;    
	\+led2_\:  INOUT  STD_LOGIC;    
	\+md1_\:   INOUT  STD_LOGIC;    
	\+md2_\:   INOUT  STD_LOGIC;    
	\+md3_\:   INOUT  STD_LOGIC;    
	\+md4_\:   INOUT  STD_LOGIC;    
	\-led1_\:  INOUT  STD_LOGIC;    
	\-led2_\:  INOUT  STD_LOGIC;    
	\-md1_\:   INOUT  STD_LOGIC;    
	\-md2_\:   INOUT  STD_LOGIC;    
	\-md3_\:   INOUT  STD_LOGIC;    
	\-md4_\:   INOUT  STD_LOGIC;    
	\mdct1_\:  INOUT  STD_LOGIC;    
	\mdct2_\:  INOUT  STD_LOGIC;    
	\mdct3_\:  INOUT  STD_LOGIC;    
	\mdct4_\:  INOUT  STD_LOGIC);
end rj45_dual_jgl_0001nl;
