// generated by newgenasym  Mon Oct 03 15:18:21 2016


module jt3_1125hl (cmct, cms_n, cms_p, led_g_n, led_g_p, led_gy_n, led_gy_p,
        trct1, trct2, trct3, trct4, trd1_n, trd1_p, trd2_n, trd2_p,
        trd3_n, trd3_p, trd4_n, trd4_p);
    inout cmct;
    inout cms_n;
    inout cms_p;
    inout led_g_n;
    inout led_g_p;
    inout led_gy_n;
    inout led_gy_p;
    inout trct1;
    inout trct2;
    inout trct3;
    inout trct4;
    inout trd1_n;
    inout trd1_p;
    inout trd2_n;
    inout trd2_p;
    inout trd3_n;
    inout trd3_p;
    inout trd4_n;
    inout trd4_p;


    initial
        begin
        end

endmodule
