-- generated by newgenasym Mon Oct 03 15:18:21 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity jt3_1125hl is
    port (    
	CMCT:      INOUT  STD_LOGIC;    
	CMS_N:     INOUT  STD_LOGIC;    
	CMS_P:     INOUT  STD_LOGIC;    
	LED_G_N:   INOUT  STD_LOGIC;    
	LED_G_P:   INOUT  STD_LOGIC;    
	LED_GY_N:  INOUT  STD_LOGIC;    
	LED_GY_P:  INOUT  STD_LOGIC;    
	TRCT1:     INOUT  STD_LOGIC;    
	TRCT2:     INOUT  STD_LOGIC;    
	TRCT3:     INOUT  STD_LOGIC;    
	TRCT4:     INOUT  STD_LOGIC;    
	TRD1_N:    INOUT  STD_LOGIC;    
	TRD1_P:    INOUT  STD_LOGIC;    
	TRD2_N:    INOUT  STD_LOGIC;    
	TRD2_P:    INOUT  STD_LOGIC;    
	TRD3_N:    INOUT  STD_LOGIC;    
	TRD3_P:    INOUT  STD_LOGIC;    
	TRD4_N:    INOUT  STD_LOGIC;    
	TRD4_P:    INOUT  STD_LOGIC);
end jt3_1125hl;
