-- generated by newgenasym Fri Aug 19 14:06:49 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_molex_0445600012 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	SHIELD1:   INOUT  STD_LOGIC;    
	SHIELD2:   INOUT  STD_LOGIC;    
	SHIELD3:   INOUT  STD_LOGIC);
end rj45_molex_0445600012;
